### ISSUE TITLE
Compat with jest

### ISSUE THREAD

**Issue by gregkonush** [klimashkin/react-size-watcher#1]
Good day to you sir! Thanks for creating a library!

I am getting an error when trying to render `SizeWatcherProvider` in the jest context
```Error: Uncaught [ReferenceError: React is not defined]```

here is the source code for the test

```
it('renders and matches snapshot', () => {
    const {baseElement} = render(
      <SizeWatcherProvider>
        <div>test</div>
      </SizeWatcherProvider>,
    );
  });
```

basically `React` default import needs to be present in component like so:

```
import React, {createElement, forwardRef, useCallback, useContext, useEffect, useReducer, useRef} from 'react';
```

**Comment by klimashkin** [comment]
Please check 2.1.1
